const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const text = fs.readFileSync(path.join(root, 'LICENSE.txt'), 'utf8').replaceAll('\r\n', '\n');
// Keep the offline interface derived from the canonical license document.
fs.writeFileSync(path.join(root, 'app/license.mjs'),
  `// Generated by scripts/sync-license.cjs from LICENSE.txt.\nexport const licenseText = ${JSON.stringify(text)};\n`);
